### ISSUE TITLE
Minor Fixes / Changes Checklist

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#102]
- [x] Make forked tongues optional for lizards
- [x] Make radstorms automatically temporarily remove maint access restrictions
- [x] Add sharks
- [ ] Borg reset modules reported not working
- [ ] Podmen not receiving light correctly
