### ISSUE TITLE
Master Porting Checklist

### ISSUE THREAD

**Issue by TalkingCactus** [citadel-station/citadel-main#40]
# Deadline is December 21, 2016
Here I will collaborate with others to create a list of everything that we wish to port from Citadel-Station-5th-Port and perhaps other repositories. Things will be subdivided into separate sub-lists. If there is something you wish to be ported, comment with this: 
**What it is:
Why we need it:
Source:**

---
# Feature List
- [x] Dogborgs
- [ ] Xenos from 5th port (definitely buffed, guys)
- [x] Kinkmate
- [x] Pokemon
- [x] Donator species
- [ ] Donator items?(I don't think we had many of these but we can try it out)
- [ ] Expanded flavor text
- [x] Screams, other sounds
- [ ] ~~Table slam~~
- [ ] Improved character preferences: Clothing, accessories, etc. (From Polaris)
- [x] Magboots in appropriate suit storage units
- [x] Plant bags of holding
- [x] Improved stickybans(I think tg already fixed this)
- [ ] Xenobotany
- [ ] Gateway missions, gateway specific content, etc.

---
# Species List
- [x] Xenomorph
- [ ] Octopus
- [x] Yautja
- [ ] Carp
- [ ] Corgi
- [ ] Cow
- [ ] Deer
- [ ] Hawk
- [ ] Leporid
- [ ] Moth
- [ ] Porcupine
- [ ] Raccoon
- [ ] Skunk
- [ ] Hylotl
- [ ] Horse
- [ ] Ursine
- [x] Squirrel
- [ ] Fungus
- [ ] Glowfen
- [ ] Crocodile
- [ ] Pandas
- [ ] Runacs

---
# Mapping List
- [ ] Maintenance Bar
- [ ] MicroStation
- [x] Button into secure engineering storage(box)

**Comment by Zeldazackman** [comment]
Kink mates because this is Citadel and the playerbase generally WILLINGLY would wear a collar.

The donator races/ items that folks donated for because its right.

Bits from the usual quality of life updates like screaming because people got used to it and genuinely enjoyed little things like this.

Dragons and pokemon because folks honestly seemed to have loved playing as those mobs on the slow days.

**Comment by TalkingCactus** [comment]
Added to the list.

**Comment by SalvageTum** [comment]
Table crafting instead of the Laggy menu

**Comment by SalvageTum** [comment]
Tis a nightmare for cooks

**Comment by TalkingCactus** [comment]
All I can suggest is to turn on the 'only show craftable recipes' option. We're not bringing back the old crafting menu just because it takes a slightly decent computer to use the new one.

**Comment by SalvageTum** [comment]
SEs having magboots in the hardsuit storage again.

**Comment by SalvageTum** [comment]
TABLE SLAMMING!

**Comment by SalvageTum** [comment]
The maint bar!
Everyone with maint access!
Fukken laspistols!

**Comment by SalvageTum** [comment]
The button next to engineering storage in case a CE doesn't show up!

**Comment by TalkingCactus** [comment]
Laser pistols are part of /tg/ now. Not exactly the same as we had them, but they're still good.

**Comment by chafla** [comment]
Auto-drone generation like in 5th port engineering
Because we had it in 5th port and 80% of the time science can't be bothered to actually put metal in the shell maker

**Comment by TalkingCactus** [comment]
I'm in the boat of: We're better off without drone shells at round-start and no auto-filled drone dispenser. Drones are a nuisance to players and often times would just be in the way. They could fulfill most jobs with all access and super speed. They were unkillable grief machines, too. I'd rather they stay on the sidelines this time.

**Comment by SalvageTum** [comment]
Having the two posibrains spawn in robotics.

**Comment by chafla** [comment]
I see, that makes sense.

**Comment by Zeldazackman** [comment]
Add back in red pandas and runacs

**Comment by SalvageTum** [comment]
The experimentor room. It's way too big in the 6th port for a room that hardly gets used. It's what, ten tiles by four? While 5th port was like four by four.

**Comment by SalvageTum** [comment]
Science Borg was pretty nifty in 5th.

**Comment by codethme** [comment]
_**audible screams**_

**Comment by TalkingCactus** [comment]
already on the list

**Comment by katnep** [comment]
The new tg crafting menu, they fixed the laggy food menu by separating the food tabs into their categories

**Comment by Poojawa** [comment]
Dogborgs Ported. updated OP.

**Comment by Poojawa** [comment]
Plant bags of holding ported.

Pokeman simple mobs ported.

**Comment by TalkingCactus** [comment]
DEADLINE FOR NEW FEATURES HAS BEEN SET FOR **DECEMBER 21, 2016**

At that point we'll update the main server with what we have.
